[package]
name = "rpncalc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0.98", features = [ "full" ] }
proc-macro2 = "1.0.40"
quote = "1.0.20"